apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibo-calc-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fibo-calc-api
  template:
    metadata:
      labels:
        app: fibo-calc-api
    spec:
      containers:
        - name: fibo-calc-api
          image: allanegidio/fibo-calc-api
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PG_USER
              value: postgress
            - name: PG_HOST
              value: portgres-cluster-ip-service
            - name: PG_PORT
              value: '5432'
            - name: PG_DATABASE
              value: postgres
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 5000
