apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgress-storage
          persistentVolumeClaim:
            claimName: database-persistent-volume-claim
      containers:
      - name: postgres
        image: postgres
        env:
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: pgsecretpassword
                key: pgsecretvalue
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5432
        volumeMounts:
          - name: postgress-storage
            mountPath: /var/lib/postgressql/data
            subPath: postgress
